site_name: wikbase extracted sparql examples
nav:
  - Home: ./index.md
  - WikiData: ./examples/wikidata/index.md
  - License: ./LICENSE.md
  - Readme: ./Code_Instructions.md
  - Status: ./status.md
site_dir: _site
theme: 
  name: windmill
  custom_dir: custom_theme/
plugins:
  - mermaid2

markdown_extensions:
  - fenced_code
